units:
# Proxy Spacing Variables
  kx: cx
  ky: cy
# Keycap size - Choc keycaps are 17.5 x 16.5
  kcx: kx - 0.5
  kcy: ky - 0.5
# Padding Variables
  px: kx + 2
  py: ky + 2
points:
   key:
      padding: ky
      footprints:
          choc_hotswap:
            type: choc
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
                hotswap: true
          choc:
            type: choc
            anchor:
              rotate: 180
            nets:
              from: =column_net
              to: GND
            params:
                keycaps: true
                reverse: true
   zones:
    board:
      rows:
        bottom:
        home:
        top:
      columns:
          pinkie:
            key:
             spread: kx
             row_overrides: 
              bottom:
                bind: [0, 0, 0, 1]
                column_net: P21
              home:
                bind: [0.5, 3, 3, 1]
                column_net: P20
          ring:
            key:
              stagger: 13
              spread: kx
            rows: 
              bottom:
                bind: [0, 0, 2, 3]
                column_net: P19
              home: 
                bind: [3,0,3,1]
                column_net: P18
              top: 
                bind: [0.5,3,0,1]
                column_net: P15
          middle:
            key: 
              stagger: 8
              spread: kx
            rows: 
              bottom:
                bind: [0, 3, 20, 3]
                column_net: P14
              home: 
                bind: [3,0,3,0]
                column_net: P16
              top:
                column_net: P10
                bind: [0.5,1,0,1]
          index: 
            key:
              stagger: -12
              spread: kx
            rows: 
              bottom:
                bind: [0, 3, 0, 0]
                column_net: P4
              home: 
                bind: [3,0,3,0]
                column_net: P5
              top: 
                bind: [0.5,1,3,3]
                column_net: P6
          far: 
            key:
              stagger: -ky - 1
              spread: kx
            rows: 
              bottom:
                bind: [3,1, 0, 73]
                column_net: P9
              home: 
                bind: [3,1,3,0]
                column_net: P7 
              top: 
                bind: [0.5,1,3,3]
                column_net: P8
outlines:
  raw:
    - what: rectangle
      where: true 
      size: [kx , ky]
  cutout:
    - what: outline
      where: true
      name: raw
      fillet: 3
  keycap_outlines:
    - what: rectangle
      where: true
      size: [kcx , kcy] # Choc keycaps are 17.5 x 16.5
      bound: false               
pcbs:
  flipper:
    outlines:
      main:
        outline: cutout
    footprints:
      promicro:
        what: promicro
        where: true
        adjust:
          ref: board_far_home
          shift: [-25, -17]
          rotate: 0
        params:
          orientation: down
      pcm12:
        what: pcm12
        where: true
        adjust:
          ref: board_far_home
          shift: [-75, -22]
          rotate: 0
        params:
          reverse: true
          from: "{{pos}}"  
          to: "{{RAW}}" 
      via3:
        what: via
        where: true
        adjust: 
          ref: board_pinkie_bottom
          shift: [-2,-10]
        params: 
          net: RAW 
      via4:
        what: via
        where: true
        adjust: 
          ref: board_pinkie_bottom
          shift: [-4,-10]
        params: 
          net: pos 
      via5:
        what: via
        where: true
        adjust: 
          ref: board_pinkie_bottom
          shift: [8,-10]
        params: 
          net: GND 
      via6:
        what: via
        where: true
        adjust: 
          ref: board_pinkie_bottom
          shift: [6,-10]
        params: 
          net: RST 
      b3u1000p:
        what: b3u1000p
        where: true
        adjust:
          ref: board_pinkie_bottom
          shift: [7, -15]
          rotate: 0
        params:
          reverse: true
          r1: RST  
          r2: GND
      bat:
        what: bat
        where: true
        params: 
          neg: GND
        adjust:
          ref: board_far_bottom
          shift: [-42 , -0]
          rotate: 0
